# -*- coding: utf-8 -*-
"""ANN_LR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bTAeq9sUlN7hW1Ocq1cYGiT3JSh6yHRM
"""

import numpy as np

# Define the Perceptron learning function
def perceptron_learning(inputs, target, weights, learning_rate=0.1, epochs=1):
    for epoch in range(epochs):
        for i in range(len(inputs)):
            # Calculate the output (step function)
            output = np.dot(inputs[i], weights)
            predicted = 1 if output >= 0 else 0

            # Update weights if there's an error
            error = target[i] - predicted
            weights += learning_rate * error * inputs[i]
    return weights

# Define inputs (3 inputs each)
inputs = np.array([[1, 1, 1], [1, 0, 1], [0, 1, 1], [0, 0, 1]])
# Define target output for OR function
target = np.array([1, 1, 1, 0])

# Initialize weights
weights = np.random.rand(3)

# Train the perceptron
new_weights = perceptron_learning(inputs, target, weights)
print("Updated Weights:", new_weights)

# Define the Hebbian learning function
def hebbian_learning(inputs, target, weights, epochs=1):
    for epoch in range(epochs):
        for i in range(len(inputs)):
            # Calculate the output
            output = np.dot(inputs[i], weights)
            predicted = 1 if output >= 0 else 0

            # Update weights based on input-output product
            weights += target[i] * inputs[i]
    return weights

# Train with Hebbian learning rule
weights_hebbian = np.random.rand(3)
new_weights_hebbian = hebbian_learning(inputs, target, weights_hebbian)
print("Hebbian Learning Updated Weights:", new_weights_hebbian)

# Define the Delta learning function
def delta_learning(inputs, target, weights, learning_rate=0.1, epochs=1):
    for epoch in range(epochs):
        for i in range(len(inputs)):
            # Calculate the output
            output = np.dot(inputs[i], weights)
            predicted = 1 if output >= 0 else 0

            # Update weights based on the error term
            error = target[i] - predicted
            weights += learning_rate * error * inputs[i]
    return weights

# Train with Delta learning rule
weights_delta = np.random.rand(3)
new_weights_delta = delta_learning(inputs, target, weights_delta)
print("Delta Learning Updated Weights:", new_weights_delta)

# Define inputs for AND logic
inputs_and = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
target_and = np.array([1, 0, 0, 0])

# Initialize weights
weights_and = np.random.rand(2)

# Train perceptron for AND
new_weights_and = perceptron_learning(inputs_and, target_and, weights_and)
print("AND Function Weights:", new_weights_and)

# Define inputs for OR logic
inputs_or = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
target_or = np.array([1, 1, 1, 0])

# Initialize weights
weights_or = np.random.rand(2)

# Train perceptron for OR
new_weights_or = perceptron_learning(inputs_or, target_or, weights_or)
print("OR Function Weights:", new_weights_or)

# Define inputs for NAND logic
inputs_nand = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
target_nand = np.array([0, 1, 1, 1])

# Initialize weights
weights_nand = np.random.rand(2)

# Train perceptron for NAND
new_weights_nand = perceptron_learning(inputs_nand, target_nand, weights_nand)
print("NAND Function Weights:", new_weights_nand)

# Define inputs for NOR logic
inputs_nor = np.array([[1, 1], [1, 0], [0, 1], [0, 0]])
target_nor = np.array([0, 0, 0, 1])

# Initialize weights
weights_nor = np.random.rand(2)

# Train perceptron for NOR
new_weights_nor = perceptron_learning(inputs_nor, target_nor, weights_nor)
print("NOR Function Weights:", new_weights_nor)



