# -*- coding: utf-8 -*-
"""24_and_grayscale_negative.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i_ZD6LqACGpUPLVf5p93I44O7pdRA089
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image

# Upload the image
uploaded = files.upload()

# Load image as RGB
for file_name in uploaded.keys():
    pil_image = Image.open(file_name).convert('RGB')
    img_rgb = np.array(pil_image)

# Generate 24-bit color negative
neg_color = 255 - img_rgb

# Display original and negative
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Original 24-bit Color Image")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(neg_color)
plt.title("24-bit Color Negative Image")
plt.axis('off')

plt.tight_layout()
plt.show()

#path version

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image
image_path = "path/to/image.jpg"
img_bgr = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

# Color negative
neg_color = 255 - img_rgb

# Display
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(img_rgb)
plt.title("Original 24-bit Color Image")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(neg_color)
plt.title("24-bit Color Negative Image")
plt.axis('off')

plt.tight_layout()
plt.show()

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image

# Upload the image
uploaded = files.upload()

# Load image as RGB
for file_name in uploaded.keys():
    pil_image = Image.open(file_name).convert('RGB')
    img_rgb = np.array(pil_image)

# Convert to grayscale
gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)

# Generate grayscale negative
neg_gray = 255 - gray

# Display original grayscale and negative
plt.figure(figsize=(10, 4))

plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title("8-bit Grayscale Image")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(neg_gray, cmap='gray')
plt.title("8-bit Grayscale Negative Image")
plt.axis('off')

plt.tight_layout()
plt.show()

#path version

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image
image_path = "path/to/image.jpg"
img_bgr = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

# Convert to grayscale
gray = cv2.cvtColor(img_rgb, cv2.COLOR_RGB2GRAY)

# Grayscale negative
neg_gray = 255 - gray

# Display
plt.figure(figsize=(10, 4))
plt.subplot(1, 2, 1)
plt.imshow(gray, cmap='gray')
plt.title("8-bit Grayscale Image")
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(neg_gray, cmap='gray')
plt.title("8-bit Grayscale Negative")
plt.axis('off')

plt.tight_layout()
plt.show()