# -*- coding: utf-8 -*-
"""geometric_transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTw6WD8ClAWeBN4qv6jDfesmF8IAI46Q
"""

import numpy as np

P = np.array([2, 3])
translation = np.array([4, 5])
P_translated = P + translation
print("Translated Point:", (int(P_translated[0]), int(P_translated[1])))

P = np.array([2, 3])
rotation_matrix = np.array([[0, -1], [1, 0]])
P_rotated = rotation_matrix @ P
print("Rotated Point:", (int(P_rotated[0]), int(P_rotated[1])))

P = np.array([3, 4])
scaling_factors = np.array([2, 3])
P_scaled = P * scaling_factors
print("Scaled Point:", (int(P_scaled[0]), int(P_scaled[1])))

P = np.array([2, 3])
shear_factor = 2
x_new = P[0] + shear_factor * P[1]
P_sheared = (int(x_new), int(P[1]))
print("Sheared Point (X-axis):", P_sheared)

