# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kt-aXNca2QNeZyKihITa8gZ-o-3LVKou
"""

# Install OpenCV if not already available
!pip install opencv-python-headless

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from IPython.display import Image, display

# Upload an image
uploaded = files.upload()

# Load the image in grayscale
for file_name in uploaded.keys():
    img = cv2.imread(file_name, cv2.IMREAD_GRAYSCALE)

# Apply Histogram Equalization
equalized_img = cv2.equalizeHist(img)

# Plotting original and equalized image and their histograms
plt.figure(figsize=(12, 6))

# Original image
plt.subplot(2, 2, 1)
plt.imshow(img, cmap='gray')
plt.title('Original Image')
plt.axis('off')

# Histogram of original image
plt.subplot(2, 2, 2)
plt.hist(img.ravel(), 256, [0, 256])
plt.title('Histogram of Original')

# Equalized image
plt.subplot(2, 2, 3)
plt.imshow(equalized_img, cmap='gray')
plt.title('Equalized Image')
plt.axis('off')

# Histogram of equalized image
plt.subplot(2, 2, 4)
plt.hist(equalized_img.ravel(), 256, [0, 256])
plt.title('Histogram of Equalized')

plt.tight_layout()
plt.show()