# -*- coding: utf-8 -*-
"""split_channels.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oe2yNJB-S0gB4ftq6R9rsUlEfzd09ZKV
"""

pip install numpy matplotlib opencv-python

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
from PIL import Image

# Step 1: Upload the image
uploaded = files.upload()

# Step 2: Load the uploaded image using PIL, then convert to NumPy and OpenCV format
for file_name in uploaded.keys():
    pil_image = Image.open(file_name).convert('RGB')
    img_rgb = np.array(pil_image)

# Step 3: Split RGB channels
R, G, B = cv2.split(img_rgb)
blank = np.zeros_like(R)

# RGB channel images
img_R = cv2.merge([R, blank, blank])
img_G = cv2.merge([blank, G, blank])
img_B = cv2.merge([blank, blank, B])

# Convert RGB to CMY (C = 255 - R, M = 255 - G, Y = 255 - B)
C = 255 - R
M = 255 - G
Y = 255 - B

# CMY channel images
img_C = cv2.merge([C, blank, blank])
img_M = cv2.merge([blank, M, blank])
img_Y = cv2.merge([blank, blank, Y])

# Step 4: Display everything
plt.figure(figsize=(12, 6))

plt.subplot(2, 4, 1)
plt.imshow(img_rgb)
plt.title("Original RGB Image")
plt.axis('off')

plt.subplot(2, 4, 2)
plt.imshow(img_R)
plt.title("Red Channel")
plt.axis('off')

plt.subplot(2, 4, 3)
plt.imshow(img_G)
plt.title("Green Channel")
plt.axis('off')

plt.subplot(2, 4, 4)
plt.imshow(img_B)
plt.title("Blue Channel")
plt.axis('off')

plt.subplot(2, 4, 6)
plt.imshow(img_C)
plt.title("Cyan Channel")
plt.axis('off')

plt.subplot(2, 4, 7)
plt.imshow(img_M)
plt.title("Magenta Channel")
plt.axis('off')

plt.subplot(2, 4, 8)
plt.imshow(img_Y)
plt.title("Yellow Channel")
plt.axis('off')

plt.tight_layout()
plt.show()

#path version

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Load the image using OpenCV
image_path = "path/to/image.jpg"
img_bgr = cv2.imread(image_path)
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

# Split RGB
R, G, B = cv2.split(img_rgb)
blank = np.zeros_like(R)

img_R = cv2.merge([R, blank, blank])
img_G = cv2.merge([blank, G, blank])
img_B = cv2.merge([blank, blank, B])

# Convert to CMY
C = 255 - R
M = 255 - G
Y = 255 - B

img_C = cv2.merge([C, blank, blank])
img_M = cv2.merge([blank, M, blank])
img_Y = cv2.merge([blank, blank, Y])

# Display
plt.figure(figsize=(12, 6))

plt.subplot(2, 4, 1)
plt.imshow(img_rgb)
plt.title("Original RGB Image")
plt.axis('off')

plt.subplot(2, 4, 2)
plt.imshow(img_R)
plt.title("Red Channel")
plt.axis('off')

plt.subplot(2, 4, 3)
plt.imshow(img_G)
plt.title("Green Channel")
plt.axis('off')

plt.subplot(2, 4, 4)
plt.imshow(img_B)
plt.title("Blue Channel")
plt.axis('off')

plt.subplot(2, 4, 6)
plt.imshow(img_C)
plt.title("Cyan Channel")
plt.axis('off')

plt.subplot(2, 4, 7)
plt.imshow(img_M)
plt.title("Magenta Channel")
plt.axis('off')

plt.subplot(2, 4, 8)
plt.imshow(img_Y)
plt.title("Yellow Channel")
plt.axis('off')

plt.tight_layout()
plt.show()



